sube: ["aumenta", "incrementa"]
baja: ["reduce", "disminuye"]
silencia: ["mutea", "silencio"]
activa: ["desmutea", "reactiva"]
saludame: ["saluda", "hola"]
apaga: ["apagar", "apágala", "apágalo"]
enciende: ["prende", "enciéndela", "enciéndelo"]
clima: ["tiempo"]
hiberna: ["suspende", "suspensión", "suspender"]
